### ISSUE TITLE
04월 04주차 과제

### ISSUE THREAD

**Issue by Jiyeon526** [SSAFY-WhyWrong/Algorithm2022#46]

**Comment by Jiyeon526** [comment]
[프로그래머스 표 편집](https://programmers.co.kr/learn/courses/30/lessons/81303)

**Comment by yyerim0901** [comment]
[16929번 Two Dots](https://www.acmicpc.net/problem/16929)

**Comment by shining8543** [comment]
[백준 3797 백조의 호수](https://www.acmicpc.net/problem/3197)
